### ISSUE TITLE
utteranc 오류

### ISSUE THREAD

**Issue by jisungbin** [BAEKJungHo/BAEKJungHo.github.io#1]
안녕하세요. "[The Road to the New Kotlin Compiler K2](https://baekjungho.github.io/wiki/kotlin/kotlin-compiler-k2/)" 게시글 큰 배움을 얻으며 잘 보았습니다. 좋은 글 감사합니다.

해당 게시글에 감사하다는 댓글을 남기려 했지만 utteranc 오류가 발생하여 알리는 게 좋을 거 같아 이슈 남깁니다.

<img width="70%" src="https://github.com/BAEKJungHo/BAEKJungHo.github.io/assets/40740128/eb4d0a83-cbce-48f2-84b7-346d78a45eaa">

```
Error: https://baekjungho.github.io is not permitted to post to BAEKJungHo/BAEKJungHo.github.io.
Confirm this is the correct repo for this site's comments. 
If you own this repo, update the utterances.json to include https://baekjungho.github.io in the list of origins.

Suggested configuration:
{
  "origins": [
    "https://baekjungho.github.io"
  ]
}
```

**Comment by BAEKJungHo** [comment]
@jisungbin 이 글을 이제서야 읽고 수정을 했습니다 ㅜㅜ. 감사합니다 !
